Store api general updates
shopware/store-api-reference pull request #2
Opened 2022-09-14 21:56 UTC by sushmangupta

Changes made are w.r.t textual, passive voice, grammatical errors, and contextual errors.

2022-09-15 12:01 UTC, Christian-Rades requested changes

2022-09-15 13:40 UTC, sushmangupta commented on docs/guides/faq.md
> +**How can I check whether I am currently logged in?**
Here the auxiliary verb is missing in the sentence:  How can I check whether the user is currently logged in?

2022-09-15 13:46 UTC, sushmangupta commented on docs/guides/faq.md
> +> The least you need in order to have logged in is, a `sw-context-token` header. In order to check whether you are actually logged in call the following endpoint
Suggesting to keep the sentence as follows: 
The least you need to get logged in is an `sw-context-token` header. In order to check whether the user is actually logged in, call the following endpoint

2022-09-15 13:52 UTC, sushmangupta commented on docs/guides/faq.md
> +> When you request include the `sw-include-seo-urls: 1` header. Shopware will automatically try to resolve relative URLs for all your categories and products. These will then be accessible in the `se
If your request includes the `sw-include-seo-urls: 1` header, Shopware will automatically try to resolve relative URLs for all your categories and products. These will then be accessible in the `seoUrls` field of each record.

2022-09-15 14:23 UTC, Christian-Rades commented on docs/guides/faq.md
> +> The least you need in order to have logged in is, a `sw-context-token` header. In order to check whether you are actually logged in call the following endpoint
Sounds good :+1:

2022-09-15 14:23 UTC, Christian-Rades commented on docs/guides/faq.md
> +> When you request include the `sw-include-seo-urls: 1` header. Shopware will automatically try to resolve relative URLs for all your categories and products. These will then be accessible in the `se
:heavy_check_mark:

2022-09-15 14:25 UTC, Christian-Rades commented on docs/guides/faq.md
> +**How can I check whether I am currently logged in?**
Do mean like this ?:
> How to check whether a user is currently logged in.

2022-09-15 14:57 UTC, sushmangupta commented on docs/guides/faq.md
> +**How can I check whether I am currently logged in?**
Yes right and with a question mark please. :)

2022-09-19 06:09 UTC, sushmangupta commented on docs/guides/quick-start/handling-the-payment.md
> +All the above transaction-related information will be assembled into a **return URL** for the external payment provider containing the token as a parameter `_sw_payment_token`. Together with this **r
Please remove this information in brackets : (neither the `finishUrl` nor the `errorUrl` - it's a Shopware endpoint\)

2022-09-19 07:28 UTC, Christian-Rades commented on docs/guides/faq.md
> +**How can I check whether I am currently logged in?**
```suggestion
**How to check whether a user is currently logged in?**
```

2022-09-22 09:00 UTC, sushmangupta commented
All changes have been made.

2022-09-22 12:27 UTC, Christian-Rades approved these changes

2022-09-22 12:27 UTC, merged